config/routes.rb
Rails.application.routes.draw do
  resources :projects

  devise_for :users

  root 'welcome#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :imprint
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @projects = user_signed_in? ? current_user.projects : Project.all
  end

  def show
    respond_with(@project)
  end

  def new
    @project = Project.new
    respond_with(@project)
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    @project.save
    respond_with(@project)
  end

  def update
    @project.update(project_params)
    respond_with(@project)
  end

  def destroy
    @project.destroy
    respond_with(@project)
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:code, :title, :series, :isbn, :copyright, :number, :author, :level,
                                      :imprint, :edition, :acronym, :product_type, :imprint_id, :budget,
                                      :image_assets, :media_assets, :text_assets, :start, :revised_start,
                                      :close, :revised_close, :printer, :revised_printer, :color, :print_run,
                                      :trim_size, :price, :free_text, :user_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to user_signed_in? ? projects_url(current_user) : projects_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MigratedPhotoApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container-fluid">
      <%= nav_bar fixed: :top, brand: 'Migrated Project', :responsive => true do %>
        <%= menu_group do  %>
          <%= menu_item 'Home', root_path  %>
          <%- if !user_signed_in?  %>
              <%= menu_item "Sign In", new_user_session_path, pull: :right  %>
          <% else %>
              <%= menu_item 'Sign out', destroy_user_session_path, method: :delete  %>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div class="clearfix"></div>
<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :series %><br>
    <%= f.text_field :series %>
  </div>
  <div class="field">
    <%= f.label :isbn %><br>
    <%= f.text_field :isbn %>
  </div>
  <div class="field">
    <%= f.label :copyright %><br>
    <%= f.text_field :copyright %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.text_field :level %>
  </div>
  <div class="field">
    <%= f.label :edition %><br>
    <%= f.text_field :edition %>
  </div>
  <div class="field">
    <%= f.label :acronym %><br>
    <%= f.text_field :acronym %>
  </div>
  <div class="field">
    <%= f.label :product_type %><br>
    <%= f.number_field :product_type %>
  </div>
  <div class="field">
    <%= f.label :imprint_id %><br>
    <%= f.text_field :imprint_id %>
  </div>
  <div class="field">
    <%= f.label :budget %><br>
    <%= f.text_field :budget %>
  </div>
  <div class="field">
    <%= f.label :image_assets %><br>
    <%= f.number_field :image_assets %>
  </div>
  <div class="field">
    <%= f.label :media_assets %><br>
    <%= f.number_field :media_assets %>
  </div>
  <div class="field">
    <%= f.label :text_assets %><br>
    <%= f.number_field :text_assets %>
  </div>
  <div class="field">
    <%= f.label :start %><br>
    <%= f.date_select :start %>
  </div>
  <div class="field">
    <%= f.label :revised_start %><br>
    <%= f.date_select :revised_start %>
  </div>
  <div class="field">
    <%= f.label :close %><br>
    <%= f.date_select :close %>
  </div>
  <div class="field">
    <%= f.label :revised_close %><br>
    <%= f.date_select :revised_close %>
  </div>
  <div class="field">
    <%= f.label :printer %><br>
    <%= f.date_select :printer %>
  </div>
  <div class="field">
    <%= f.label :revised_printer %><br>
    <%= f.date_select :revised_printer %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :print_run %><br>
    <%= f.text_field :print_run %>
  </div>
  <div class="field">
    <%= f.label :trim_size %><br>
    <%= f.text_field :trim_size %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :free_text %><br>
    <%= f.text_area :free_text %>
  </div>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing Projects</h1>

<table class="table">
  <thead>
    <tr>
      <th>Code</th>
      <th>Title</th>
      <th>Series</th>
      <th>Isbn</th>
      <th>Copyright</th>
      <th>Number</th>
      <th>Author</th>
      <th>Level</th>
      <th>Imprint</th>
      <th>Edition</th>
      <th>Acronym</th>
      <th>Product type</th>
      <th>Budget</th>
      <th>Image assets</th>
      <th>Media assets</th>
      <th>Text assets</th>
      <th>Start</th>
      <th>Revised start</th>
      <th>Close</th>
      <th>Revised close</th>
      <th>Printer</th>
      <th>Revised printer</th>
      <th>Color</th>
      <th>Print run</th>
      <th>Trim size</th>
      <th>Price</th>
      <th>Free text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.code %></td>
        <td><%= project.title %></td>
        <td><%= project.series %></td>
        <td><%= project.isbn %></td>
        <td><%= project.copyright %></td>
        <td><%= project.number %></td>
        <td><%= project.author %></td>
        <td><%= project.level %></td>
        <td><%= project.imprint %></td>
        <td><%= project.edition %></td>
        <td><%= project.acronym %></td>
        <td><%= project.product_type %></td>
        <td><%= project.budget %></td>
        <td><%= project.image_assets %></td>
        <td><%= project.media_assets %></td>
        <td><%= project.text_assets %></td>
        <td><%= project.start %></td>
        <td><%= project.revised_start %></td>
        <td><%= project.close %></td>
        <td><%= project.revised_close %></td>
        <td><%= project.printer %></td>
        <td><%= project.revised_printer %></td>
        <td><%= project.color %></td>
        <td><%= project.print_run %></td>
        <td><%= project.trim_size %></td>
        <td><%= project.price %></td>
        <td><%= project.free_text %></td>
        <% if user_signed_in? %>
            <td><%= link_to 'Show', project, class: 'btn btn-primary color-white' %></td>
            <td><%= link_to 'Edit', edit_project_path(project), class: 'btn btn-primary color-white' %></td>
            <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger color-white' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
    <%= link_to 'New Project', new_project_path, class: 'btn btn-primary color-white' %>
<% end %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @project.code %>
</p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Series:</strong>
  <%= @project.series %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @project.isbn %>
</p>

<p>
  <strong>Copyright:</strong>
  <%= @project.copyright %>
</p>

<p>
  <strong>Number:</strong>
  <%= @project.number %>
</p>

<p>
  <strong>Author:</strong>
  <%= @project.author %>
</p>

<p>
  <strong>Level:</strong>
  <%= @project.level %>
</p>

<p>
  <strong>Edition:</strong>
  <%= @project.edition %>
</p>

<p>
  <strong>Acronym:</strong>
  <%= @project.acronym %>
</p>

<p>
  <strong>Product type:</strong>
  <%= @project.product_type %>
</p>

<p>
  <strong>Imprint:</strong>
  <%= @project.imprint %>
</p>

<p>
  <strong>Budget:</strong>
  <%= @project.budget %>
</p>

<p>
  <strong>Image assets:</strong>
  <%= @project.image_assets %>
</p>

<p>
  <strong>Media assets:</strong>
  <%= @project.media_assets %>
</p>

<p>
  <strong>Text assets:</strong>
  <%= @project.text_assets %>
</p>

<p>
  <strong>Start:</strong>
  <%= @project.start %>
</p>

<p>
  <strong>Revised start:</strong>
  <%= @project.revised_start %>
</p>

<p>
  <strong>Close:</strong>
  <%= @project.close %>
</p>

<p>
  <strong>Revised close:</strong>
  <%= @project.revised_close %>
</p>

<p>
  <strong>Printer:</strong>
  <%= @project.printer %>
</p>

<p>
  <strong>Revised printer:</strong>
  <%= @project.revised_printer %>
</p>

<p>
  <strong>Color:</strong>
  <%= @project.color %>
</p>

<p>
  <strong>Print run:</strong>
  <%= @project.print_run %>
</p>

<p>
  <strong>Trim size:</strong>
  <%= @project.trim_size %>
</p>

<p>
  <strong>Price:</strong>
  <%= @project.price %>
</p>

<p>
  <strong>Free text:</strong>
  <%= @project.free_text %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>